language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

before_install:
  - openssl aes-256-cbc -K $encrypted_c86d29a4a6cb_key -iv $encrypted_c86d29a4a6cb_iv -in test-credentials.tar.enc -out test-credentials.tar -d
  - tar xvf test-credentials.tar
